language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: UMDRp31Xyb1JkDUbpi3OqGfL79VNXuFud4Hpuduv7AP+BkEx17lKT9CUvRZHMfMbyfS2zcZ8m/OtZgS0RSn38aX6W/lCGKpwkv7W3yN6dwe3cMSwxAJOkMe4cTG9K3kqrAE4NgBQS0TXtwhRDoJP5Tu8aX80vt1lsxicxjsJWCHnNF8m9G7xbbuABOe7C8qQdermCHcb/hP3nnyiaLqVWpV6A992tu2vmKYLIt2TizVUDq7ld6yCOQnK9uWWI1n8Nk9t7ZZ03VBvfwqYHPbwAGtnueP6WDE+Km6qV5BitMSON1/ZV+bJd6T8q+EbMdXx2XnxhQ5SsGfBaYA9TDcyJHbkGahS+n+IngfrCM/Q9XLyBf1aClbzJ1aTQCz8EB+SM3ZE0SuoX+FPk4sP+FaXaML64fEa7kXYWzC3qhBXAHZ1NmmkqX3gVd4MeKSs71HEOSnocDoS2lLLS+oSl3dC9qPT1Pon+ZbA0E2jUvooddCBC/v+dcelvK2qX0PaL8fQ2HIpMHQnT2gAP9ORID4dDA1dAXNrlAnezG4ZXLo/t4KvYeFF5JuoRpkqkxeqzeeVX6dRFY0S46llTQ1+LfNVqrf6wC5tHfewEuYltAftuhitIF1Ukv68FOi/qj7WpXpnlqtfHxmEd3l2MUjRJXwqN0OnbrfMF7F6iaE1NS4GQ0A=
  app: fullstack-capstone
  on:
    repo: ellendunn/fullstack-capstone-client
